pr: ["master"]

jobs:
  - job:
    strategy:
      matrix:
        mac:
          imageName: 'macos-10.13'
        windows:
          imageName: 'vs2017-win2016'
        linux:
          imageName: 'ubuntu-16.04'
    pool:
      vmImage: $(imageName)
    steps:
      - bash: brew install cairo
        condition: eq(variables['Agent.OS'], 'Darwin')

      - bash: sudo apt-get install libcairo2
        condition: eq(variables['Agent.OS'], 'Linux')

      - task: DownloadGitHubRelease@0
        inputs:
          userRepository: preshing/cairo-windows
          defaultVersionType: 'latest'
          itemPattern: '*.zip'
        condition: eq(variables['Agent.OS'], 'Windows_NT')

      - task: ExtractFiles@1
        inputs:
          archiveFilePatterns: cairo-windows-1.15.12.zip
        condition: eq(variables['Agent.OS'], 'Windows_NT')

      - template: ci/install-rust.yml
        parameters:
          rust_version: stable

      - template: ci/test.yml
        parameters:
          toolchain: stable

      - template: ci/test.yml
        parameters:
          toolchain: nightly
